/**
 * Daily Spark — deterministic couple question of the day.
 *
 * 60 curated questions per locale, written natively (not machine-translated),
 * ranging from sweet to lightly spicy. The day's question is picked with a
 * deterministic day-of-year hash so both partners see the same question on
 * the same day, in their own language, with no server round-trip.
 */

export type SparkLocale = 'en' | 'es' | 'fr' | 'pt';

const QUESTIONS: Record<SparkLocale, string[]> = {
  en: [
    "What little thing did I do this week that made you smile?",
    "If we could teleport anywhere for dinner tonight, where are we eating?",
    "What song instantly makes you think of us?",
    "What's one thing you were nervous to tell me when we first met?",
    "Which of my quirks did you find weird at first but love now?",
    "What does your perfect lazy Sunday with me look like?",
    "What's a compliment I gave you that you still think about?",
    "If our love story were a movie, what would the title be?",
    "What's one adventure you want us to have before the year ends?",
    "When did you first realize you were falling for me?",
    "What's something I do that makes you feel safe?",
    "If you could relive one of our dates, which one would it be?",
    "What's a tiny habit of mine you secretly find adorable?",
    "What would you cook for me if you wanted to impress me tonight?",
    "What's one dream you've never said out loud — until now?",
    "How would you describe me in three words to a stranger?",
    "What's the most spontaneous thing you'd do with me right now?",
    "Which photo of us is your favorite, and why?",
    "What's one way I could love you better this week?",
    "If we had a couples' bucket list, what goes at the top?",
    "What smell instantly reminds you of me?",
    "What's the best gift I've ever given you — big or small?",
    "Where do you picture us five years from now, on a random Tuesday?",
    "What's something you admire about me that I don't see in myself?",
    "If tonight were our first date again, where would you take me?",
    "What's a secret talent of yours I still haven't discovered?",
    "When do you find me most attractive without me trying?",
    "What's one thing you'd love to hear me say more often?",
    "If we ran away for a weekend right now, where are we going?",
    "What moment made you proudest to be with me?",
    "What's your favorite way I say 'I love you' without words?",
    "Which fictional couple are we most like, honestly?",
    "What's one thing about my laugh, voice, or eyes you can't resist?",
    "If we made a pact to try something new every month, what's first?",
    "What did you think the first time you saw me?",
    "What's a small ritual of ours you never want us to lose?",
    "What outfit of mine do you wish I wore more often?",
    "What's the silliest thing we've ever argued about?",
    "If I planned a surprise for you tomorrow, what would you hope it is?",
    "What part of the day do you miss me the most?",
    "What's one question you've always wanted to ask me but haven't?",
    "How do you want to be kissed after a long, exhausting day?",
    "What's a memory of us that always makes you laugh?",
    "If we wrote vows today, what's one line you'd include?",
    "What's the most romantic thing you've ever wanted to do for me?",
    "When we're old and gray, what do you hope we're still doing together?",
    "What's your favorite spot to be touched when you need comforting?",
    "What's one thing you'd love us to slow down and savor more?",
    "If our chemistry had a flavor, what would it taste like?",
    "What's something new you'd love to try together — no judgment?",
    "What do I do that instantly turns a bad day around for you?",
    "Where on your body do you love my hands the most?",
    "What's a date idea you've been quietly hoping I'd plan?",
    "What's the sweetest thing I've said to you half-asleep?",
    "If we had a secret code word for 'let's leave and be alone', what would it be?",
    "What's one fantasy trip you want us to actually book someday?",
    "What made you choose me — out of everyone?",
    "What's your favorite way we make up after a disagreement?",
    "What's one promise you want us to make to each other today?",
    "If tonight had no rules and no plans, what would you want us to do?",
  ],
  es: [
    "¿Qué pequeño detalle hice esta semana que te hizo sonreír?",
    "Si pudiéramos teletransportarnos a cenar a cualquier lugar esta noche, ¿dónde estaríamos?",
    "¿Qué canción te hace pensar en nosotros al instante?",
    "¿Qué te daba nervios contarme cuando nos conocimos?",
    "¿Cuál de mis manías te pareció rara al principio y ahora te encanta?",
    "¿Cómo sería tu domingo perfecto de pereza conmigo?",
    "¿Qué cumplido te dije que todavía recuerdas?",
    "Si nuestra historia de amor fuera una película, ¿cómo se titularía?",
    "¿Qué aventura quieres que vivamos antes de que acabe el año?",
    "¿Cuándo te diste cuenta de que te estabas enamorando de mí?",
    "¿Qué hago yo que te hace sentir en un lugar seguro?",
    "Si pudieras revivir una de nuestras citas, ¿cuál sería?",
    "¿Qué pequeño hábito mío te parece adorable en secreto?",
    "¿Qué me cocinarías esta noche si quisieras impresionarme?",
    "¿Qué sueño nunca has dicho en voz alta... hasta ahora?",
    "¿Cómo me describirías en tres palabras a un desconocido?",
    "¿Qué es lo más espontáneo que harías conmigo ahora mismo?",
    "¿Cuál es tu foto favorita de nosotros y por qué?",
    "¿De qué manera podría quererte mejor esta semana?",
    "Si tuviéramos una lista de deseos en pareja, ¿qué iría primero?",
    "¿Qué olor te recuerda a mí al instante?",
    "¿Cuál es el mejor regalo que te he dado, grande o pequeño?",
    "¿Dónde nos imaginas dentro de cinco años, un martes cualquiera?",
    "¿Qué admiras de mí que yo no veo en mí?",
    "Si esta noche fuera otra vez nuestra primera cita, ¿a dónde me llevarías?",
    "¿Qué talento oculto tuyo todavía no he descubierto?",
    "¿Cuándo te parezco más atractivo/a sin proponérmelo?",
    "¿Qué te encantaría que te dijera más a menudo?",
    "Si nos escapáramos un fin de semana ahora mismo, ¿a dónde iríamos?",
    "¿Qué momento te hizo sentir más orgullo de estar conmigo?",
    "¿Cuál es tu forma favorita en la que digo 'te quiero' sin palabras?",
    "Sinceramente, ¿a qué pareja de ficción nos parecemos más?",
    "¿Qué hay en mi risa, mi voz o mis ojos que no puedes resistir?",
    "Si hiciéramos un pacto de probar algo nuevo cada mes, ¿qué sería lo primero?",
    "¿Qué pensaste la primera vez que me viste?",
    "¿Qué pequeño ritual nuestro no quieres que perdamos nunca?",
    "¿Qué ropa mía te gustaría que me pusiera más a menudo?",
    "¿Qué es lo más tonto por lo que hemos discutido?",
    "Si mañana te preparara una sorpresa, ¿qué te gustaría que fuera?",
    "¿En qué momento del día me echas más de menos?",
    "¿Qué pregunta siempre has querido hacerme y nunca me has hecho?",
    "¿Cómo quieres que te bese después de un día largo y agotador?",
    "¿Qué recuerdo nuestro te hace reír siempre?",
    "Si escribiéramos nuestros votos hoy, ¿qué frase incluirías?",
    "¿Qué es lo más romántico que has querido hacer por mí?",
    "Cuando seamos viejitos, ¿qué esperas que sigamos haciendo juntos?",
    "¿Dónde te gusta que te acaricie cuando necesitas consuelo?",
    "¿Qué te gustaría que saboreáramos más despacio los dos?",
    "Si nuestra química tuviera un sabor, ¿a qué sabría?",
    "¿Qué te encantaría que probáramos juntos, sin juicios?",
    "¿Qué hago yo que te arregla al instante un mal día?",
    "¿En qué parte de tu cuerpo te gustan más mis manos?",
    "¿Qué plan de cita llevas tiempo esperando en secreto que organice?",
    "¿Qué es lo más dulce que te he dicho medio dormido/a?",
    "Si tuviéramos una palabra clave secreta para 'vámonos a estar solos', ¿cuál sería?",
    "¿Qué viaje de fantasía quieres que reservemos algún día de verdad?",
    "¿Qué te hizo elegirme a mí, entre todas las personas?",
    "¿Cuál es tu forma favorita de reconciliarnos después de una discusión?",
    "¿Qué promesa quieres que nos hagamos hoy?",
    "Si esta noche no tuviera reglas ni planes, ¿qué querrías que hiciéramos?",
  ],
  fr: [
    "Quelle petite chose ai-je faite cette semaine qui t'a fait sourire ?",
    "Si on pouvait se téléporter n'importe où pour dîner ce soir, on mangerait où ?",
    "Quelle chanson te fait instantanément penser à nous ?",
    "Qu'est-ce que tu n'osais pas me dire quand on s'est rencontrés ?",
    "Laquelle de mes manies t'a semblé bizarre au début et te plaît maintenant ?",
    "À quoi ressemble ton dimanche paresseux parfait avec moi ?",
    "Quel compliment de ma part te revient encore en tête ?",
    "Si notre histoire d'amour était un film, quel serait son titre ?",
    "Quelle aventure veux-tu qu'on vive avant la fin de l'année ?",
    "Quand as-tu compris que tu étais en train de tomber amoureux(se) de moi ?",
    "Qu'est-ce que je fais qui te donne un sentiment de sécurité ?",
    "Si tu pouvais revivre un de nos rendez-vous, lequel choisirais-tu ?",
    "Quelle petite habitude à moi trouves-tu secrètement adorable ?",
    "Que me cuisinerais-tu ce soir pour m'impressionner ?",
    "Quel rêve n'as-tu jamais dit à voix haute... jusqu'à maintenant ?",
    "Comment me décrirais-tu en trois mots à un inconnu ?",
    "Quelle est la chose la plus spontanée que tu ferais avec moi là, tout de suite ?",
    "Quelle est ta photo préférée de nous, et pourquoi ?",
    "Comment pourrais-je mieux t'aimer cette semaine ?",
    "Si on avait une bucket list de couple, qu'est-ce qu'on mettrait en premier ?",
    "Quelle odeur te fait instantanément penser à moi ?",
    "Quel est le plus beau cadeau que je t'ai fait, petit ou grand ?",
    "Où nous imagines-tu dans cinq ans, un mardi ordinaire ?",
    "Qu'admires-tu chez moi que je ne vois pas moi-même ?",
    "Si ce soir était à nouveau notre premier rendez-vous, tu m'emmènerais où ?",
    "Quel talent caché as-tu que je n'ai pas encore découvert ?",
    "À quel moment me trouves-tu le plus séduisant(e) sans que je fasse d'effort ?",
    "Qu'aimerais-tu que je te dise plus souvent ?",
    "Si on s'évadait en week-end là maintenant, on irait où ?",
    "Quel moment t'a rendu(e) le plus fier(ère) d'être avec moi ?",
    "Quelle est ta façon préférée dont je dis « je t'aime » sans les mots ?",
    "Honnêtement, à quel couple de fiction ressemble-t-on le plus ?",
    "Qu'est-ce que tu ne peux pas résister dans mon rire, ma voix ou mes yeux ?",
    "Si on faisait le pacte d'essayer une nouveauté chaque mois, on commence par quoi ?",
    "Qu'as-tu pensé la première fois que tu m'as vu(e) ?",
    "Quel petit rituel à nous ne veux-tu jamais qu'on perde ?",
    "Quelle tenue à moi aimerais-tu que je porte plus souvent ?",
    "Quelle est la dispute la plus ridicule qu'on ait jamais eue ?",
    "Si je te préparais une surprise demain, tu espérerais quoi ?",
    "À quel moment de la journée est-ce que je te manque le plus ?",
    "Quelle question as-tu toujours voulu me poser sans jamais oser ?",
    "Comment veux-tu être embrassé(e) après une longue journée épuisante ?",
    "Quel souvenir de nous te fait rire à tous les coups ?",
    "Si on écrivait nos vœux aujourd'hui, quelle phrase y mettrais-tu ?",
    "Quelle est la chose la plus romantique que tu aies eu envie de faire pour moi ?",
    "Quand on sera vieux et grisonnants, qu'espères-tu qu'on fasse encore ensemble ?",
    "Où aimes-tu être caressé(e) quand tu as besoin de réconfort ?",
    "Qu'aimerais-tu qu'on prenne le temps de savourer davantage à deux ?",
    "Si notre alchimie avait un goût, ce serait lequel ?",
    "Qu'aimerais-tu qu'on essaie ensemble, sans aucun jugement ?",
    "Qu'est-ce que je fais qui transforme instantanément ta mauvaise journée ?",
    "À quel endroit de ton corps préfères-tu mes mains ?",
    "Quelle idée de rendez-vous espères-tu en secret que j'organise ?",
    "Quelle est la chose la plus douce que je t'ai dite à moitié endormi(e) ?",
    "Si on avait un code secret pour « partons, rien que nous deux », ce serait quoi ?",
    "Quel voyage de rêve veux-tu qu'on réserve vraiment un jour ?",
    "Qu'est-ce qui t'a fait me choisir moi, parmi tout le monde ?",
    "Quelle est ta façon préférée de se réconcilier après une dispute ?",
    "Quelle promesse veux-tu qu'on se fasse aujourd'hui ?",
    "Si cette nuit n'avait ni règles ni programme, tu voudrais qu'on fasse quoi ?",
  ],
  pt: [
    "Que pequeno gesto meu te fez sorrir esta semana?",
    "Se pudéssemos nos teletransportar para jantar em qualquer lugar hoje, onde estaríamos?",
    "Que música te faz pensar na gente na hora?",
    "O que você ficou com receio de me contar quando nos conhecemos?",
    "Qual mania minha você achou estranha no começo e hoje adora?",
    "Como seria seu domingo preguiçoso perfeito comigo?",
    "Qual elogio meu você ainda guarda na memória?",
    "Se a nossa história de amor fosse um filme, qual seria o título?",
    "Que aventura você quer que a gente viva antes do fim do ano?",
    "Quando você percebeu que estava se apaixonando por mim?",
    "O que eu faço que te faz sentir em segurança?",
    "Se pudesse reviver um dos nossos encontros, qual seria?",
    "Que pequeno hábito meu você secretamente acha adorável?",
    "O que você cozinharia para mim hoje se quisesse me impressionar?",
    "Que sonho você nunca disse em voz alta... até agora?",
    "Como você me descreveria em três palavras para um estranho?",
    "Qual é a coisa mais espontânea que você faria comigo agora mesmo?",
    "Qual é a sua foto favorita nossa, e por quê?",
    "De que jeito eu poderia te amar melhor esta semana?",
    "Se tivéssemos uma lista de sonhos de casal, o que viria em primeiro?",
    "Que cheiro te lembra de mim na hora?",
    "Qual foi o melhor presente que eu já te dei, grande ou pequeno?",
    "Onde você nos imagina daqui a cinco anos, numa terça-feira qualquer?",
    "O que você admira em mim que eu não enxergo em mim mesmo(a)?",
    "Se hoje fosse de novo o nosso primeiro encontro, aonde você me levaria?",
    "Que talento escondido seu eu ainda não descobri?",
    "Quando você me acha mais atraente sem que eu esteja tentando?",
    "O que você adoraria me ouvir dizer mais vezes?",
    "Se fugíssemos num fim de semana agora, para onde iríamos?",
    "Que momento te deu mais orgulho de estar comigo?",
    "Qual é o seu jeito favorito de eu dizer 'eu te amo' sem palavras?",
    "Sinceramente, com qual casal de ficção a gente mais se parece?",
    "O que no meu riso, na minha voz ou nos meus olhos você não resiste?",
    "Se fizéssemos um pacto de tentar algo novo todo mês, qual seria o primeiro?",
    "O que você pensou na primeira vez que me viu?",
    "Que pequeno ritual nosso você nunca quer que a gente perca?",
    "Que roupa minha você queria que eu usasse mais vezes?",
    "Qual foi a briga mais boba que a gente já teve?",
    "Se eu preparasse uma surpresa para você amanhã, o que você gostaria que fosse?",
    "Em que momento do dia você sente mais a minha falta?",
    "Que pergunta você sempre quis me fazer e nunca fez?",
    "Como você quer ser beijado(a) depois de um dia longo e cansativo?",
    "Que lembrança nossa sempre te faz rir?",
    "Se escrevêssemos nossos votos hoje, que frase você incluiria?",
    "Qual é a coisa mais romântica que você já quis fazer por mim?",
    "Quando formos velhinhos, o que você espera que a gente ainda faça juntos?",
    "Onde você gosta de carinho quando precisa de conforto?",
    "O que você queria que a gente saboreasse com mais calma?",
    "Se a nossa química tivesse um sabor, qual seria?",
    "O que você adoraria experimentar comigo, sem julgamentos?",
    "O que eu faço que conserta na hora um dia ruim seu?",
    "Em que parte do seu corpo você mais gosta das minhas mãos?",
    "Que ideia de encontro você anda torcendo em segredo para eu planejar?",
    "Qual foi a coisa mais fofa que eu já te disse meio dormindo?",
    "Se tivéssemos um código secreto para 'vamos embora ficar sozinhos', qual seria?",
    "Que viagem dos sonhos você quer que a gente reserve de verdade um dia?",
    "O que te fez me escolher, entre todas as pessoas?",
    "Qual é o seu jeito favorito de fazermos as pazes depois de uma discussão?",
    "Que promessa você quer que a gente faça um ao outro hoje?",
    "Se esta noite não tivesse regras nem planos, o que você ia querer que a gente fizesse?",
  ],
};

const QUESTION_COUNT = 60;

/** Normalize any i18next language tag ("pt-BR", "es-419"...) to a SparkLocale. */
export function toSparkLocale(language: string | undefined): SparkLocale {
  const base = (language || 'en').toLowerCase().split('-')[0];
  return (['en', 'es', 'fr', 'pt'].includes(base) ? base : 'en') as SparkLocale;
}

/** Day-of-year (1-366) for a local date. */
function dayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  return Math.floor((date.getTime() - start.getTime()) / 86_400_000);
}

/**
 * Deterministic index for the day. Mixing in the year keeps the yearly cycle
 * from repeating in the exact same order.
 */
export function sparkIndexForDate(date: Date = new Date()): number {
  const n = dayOfYear(date) * 31 + date.getFullYear() * 17;
  return ((n % QUESTION_COUNT) + QUESTION_COUNT) % QUESTION_COUNT;
}

/** Today's Daily Spark question for a locale. */
export function getDailySpark(language: string | undefined, date: Date = new Date()): string {
  const locale = toSparkLocale(language);
  return QUESTIONS[locale][sparkIndexForDate(date)];
}

/** Local YYYY-MM-DD key used for streak/share bookkeeping. */
export function localDayKey(date: Date = new Date()): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}
